{% set name = "xframe" %}
{% set version = "0.0.2" %}
{% set sha256 = "29aec66264480e6b378155223a80642f58cecb2a964281a222de46f4cd97e670" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/QuantStack/xframe/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2000
  skip: True  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - xtensor >=0.19.1,<0.20
  run:
    - xtensor >=0.19.1,<0.20

test:
  commands:
    - test -d ${PREFIX}/include/xframe  # [unix]
    - test -f ${PREFIX}/include/xframe/xvariable.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xframe/xframeConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xframe/xframeConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\xframe\xvariable.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\xframeConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\xframeConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://quantstack.net/xframe
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'C++ dataframe'
  description: 'C++ data frame based on xtensor'
  doc_url: http://xframe.readthedocs.io
  dev_url: https://github.com/QuantStack/xframe

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
