appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: JYCAwtYGfsJ0/kSS005bK+KMDfwOj0f5uDPzCCzNhcnfAdIlKomQeJBpt7Ks8nfjp/3DzgSMGEcFGIPYbJyAUO6fZQZBdZtUzC0ySiSsGJxpOpvdNbJiMO2pZJDwFBGWlEVFbnG4LXFw7daJcVjKeUkJEK0RWchS2kj8CQDhQBMeckTYt6gGIsHjQm06tkzxf+hWK8y8vjzeGmoX8NHCksLdUU80W2bwRjtdQTZKR5sspBH5Eq/8J1xlz7MXLgbWyiTa920bx4Uq/Pb4louZkrEtbTsYRn8GkYBZmBXtEetzqOX9y1pob0nwr+99cUqPFXFaUSSPjyRHrMeOXJjjjDs8FpQv1DcaS0KpLirOYHk/7RFovjRZpnr7GNRn4us7pK8AHfQu96gwKrNeatcBNfSrMaMSHiirNCggxXYx8WrWcN01I1J6Xg3KgmbTAsCq1FJNSu1GiWvLyRimAIf6zmISCQBmxtrZQHeiJPGHCjFeTpp4bkdtLdAVOZ91li067bE1B8ZTalEmMlb79LrylulUOkQjfsoAH1Jd1iRelJcqONPZtmNCJZyhxlAD5fCTFsTmMIZsQkgonczFJrTFQ0nC8gDtVF23SWEHRZ00mXoj3KsVirGK3bIDGHz/Iu/tIYk991fa36cEdbexNa++Hbry/qbF9kUWzL5OAXWkxGc=}
provider:
  win: azure
conda_forge_output_validation: true
